apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: mattreindt/easytrade-calculationservice
      context: src/calculationservice
    - image: mattreindt/easytrade-contentcreator
      context: src/contentcreator
    - image: mattreindt/easytrade-db
      context: src/db
    - image: mattreindt/easytrade-feature-flag-service
      context: src/feature-flag-service
    - image: mattreindt/easytrade-frontend
      context: src/frontend
    - image: mattreindt/easytrade-frontendreverseproxy
      context: src/frontendreverseproxy
    - image: mattreindt/easytrade-loginservice
      context: src/loginservice
    - image: mattreindt/easytrade-manager
      context: src/manager/easyTradeManager
    - image: mattreindt/easytrade-pricing-service
      context: src/pricing-service
    - image: mattreindt/easytrade-rabbitmq
      context: src/rabbitmq
    - image: mattreindt/easytrade-offerservice
      context: src/offerservice
    - image: mattreindt/easytrade-accountservice
      context: src/accountservice
    - image: mattreindt/easytrade-aggregator-service
      context: src/aggregator-service
    - image: mattreindt/easytrade-engine
      context: src/engine
    - image: mattreindt/easytrade-credit-card-order-service
      context: src/credit-card-order-service
    - image: mattreindt/easytrade-third-party-service
      context: src/third-party-service
    - image: mattreindt/easytrade-broker-service
      context: src/broker-service
    - image: mattreindt/easytrade-loadgen
      context: src/loadgen
    - image: mattreindt/easytrade-problem-operator
      context: src/problem-operator
  tagPolicy:
    gitCommit: { ignoreChanges: true }
  local:
    concurrency: 4
    push: false
    tryImportMissing: true
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl: {}
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/base
profiles:
  - name: aws-live
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-live
  - name: aws-live-ld
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-live-ld
  - name: aws-staging
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-staging
  - name: aws-staging-ld
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-staging-ld
  - name: aws-playground
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-playground
  - name: aws-playground-staging
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ../easytrade-infrastructure/kubernetes-manifests/aws-playground-staging
