name: Build easytrade on master
on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - .github/**
      - kubernetes-manifests/**
      - skaffold.yaml
      - src/**

env:
  DOCKERHUB_REPO: mattreindt/easytrade
  SKAFFOLD_DEFAULT_REPO: mattreindt/easytrade
  SKAFFOLD_VERSION: 2.13.2

jobs:
  build-easytrade:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send build start event to Dynatrace
        run: |
          curl -X POST "${{ secrets.DT_URL }}/platform/ingest/v1/events.sdlc" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "[{
              \"event.kind\": \"SDLC_EVENT\",
              \"event.category\": \"task\", 
              \"event.type\": \"build\",
              \"event.status\": \"started\",
              \"task.name\": \"build-easytrade\",
              \"vcs.repository.name\": \"easytrade\",
              \"vcs.revision\": \"$GITHUB_SHA\",
              \"vcs.ref.name\": \"$GITHUB_REF_NAME\",
              \"cicd.pipeline.name\": \"$GITHUB_WORKFLOW\",
              \"cicd.pipeline.run.id\": \"$GITHUB_RUN_ID\",
              \"cicd.system\": \"GitHub Actions\"
            }]"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set application version
        uses: ./.github/actions/set-version
        with:
          version: 1.2.${{ github.run_number }}

      - name: "Build easytrade and push it to Docker registry with commit tag"
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: build
          push: true
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          default-repo: ${{ env.DOCKERHUB_REPO }}

      - name: "Build easytrade and push it to Docker registry with latest tag"
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: build
          tag: latest
          push: true
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          default-repo: ${{ env.DOCKERHUB_REPO }}

      - name: Send build success event to Dynatrace
        if: success()
        run: |
          curl -X POST "${{ secrets.DT_URL }}/platform/ingest/v1/events.sdlc" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "[{
              \"event.kind\": \"SDLC_EVENT\",
              \"event.category\": \"task\",
              \"event.type\": \"build\",
              \"event.status\": \"finished\",
              \"event.status.details\": \"success\",
              \"task.name\": \"build-easytrade\",
              \"vcs.repository.name\": \"easytrade\",
              \"vcs.revision\": \"$GITHUB_SHA\",
              \"vcs.ref.name\": \"$GITHUB_REF_NAME\",
              \"cicd.pipeline.name\": \"$GITHUB_WORKFLOW\",
              \"cicd.pipeline.run.id\": \"$GITHUB_RUN_ID\",
              \"cicd.system\": \"GitHub Actions\"
            }]"

      - name: Send build failure event to Dynatrace
        if: failure()
        run: |
          curl -X POST "${{ secrets.DT_URL }}/platform/ingest/v1/events.sdlc" \
            -H "Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "[{
              \"event.kind\": \"SDLC_EVENT\",
              \"event.category\": \"task\",
              \"event.type\": \"build\",
              \"event.status\": \"finished\",
              \"event.status.details\": \"failure\",
              \"task.name\": \"build-easytrade\",
              \"vcs.repository.name\": \"easytrade\",
              \"vcs.revision\": \"$GITHUB_SHA\",
              \"vcs.ref.name\": \"$GITHUB_REF_NAME\",
              \"cicd.pipeline.name\": \"$GITHUB_WORKFLOW\",
              \"cicd.pipeline.run.id\": \"$GITHUB_RUN_ID\",
              \"cicd.system\": \"GitHub Actions\"
            }]"


