name: Build easytrade on master
on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - .github/**
      - kubernetes-manifests/**
      - skaffold.yaml
      - src/**

env:
  DOCKERHUB_REPO: mattreindt/easytrade
  SKAFFOLD_DEFAULT_REPO: mattreindt/easytrade
  SKAFFOLD_VERSION: 2.13.2

jobs:
  build-easytrade:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set application version
        uses: ./.github/actions/set-version
        with:
          version: 1.2.${{ github.run_number }}

      - name: "Build easytrade and push it to Docker registry with commit tag"
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: build
          push: true
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          default-repo: ${{ env.DOCKERHUB_REPO }}

      - name: "Build easytrade and push it to Docker registry with latest tag"
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: build
          tag: latest
          push: true
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          default-repo: ${{ env.DOCKERHUB_REPO }}


      - name: Run validation
        uses: ./.github/actions/run-validation
        with:
          client_id: ${{ secrets.OQR_CLIENT_ID }}
          client_secret: ${{ secrets.OQR_CLIENT_SECRET }}
          sso_url: ${{ secrets.SSO_URL }}
          tenant_url: ${{ secrets.OQR_URL }}

      - name: Disable test environment
        run: |
          kubectl -n ${{ env.NAMESPACE }} rollout undo deployment/credit-card-order-service deployment/third-party-service
